package VistaControlador;

import Modelo.*;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class VentanaLogin extends javax.swing.JFrame {

    public void vibrarPantalla() {
        final int originalX = this.getLocationOnScreen().x;  // Obtener la posición original en X
        final int originalY = this.getLocationOnScreen().y;  // Obtener la posición original en Y
 
        // Creamos un hilo para que no bloquee el hilo principal de la UI
        new Thread(() -> {
            try {
                for (int i = 0; i < 10; i++) {
                    // Mover la ventana a posiciones levemente distintas
                    this.setLocation(originalX + (int) (Math.random() * 10 - 5),
                            originalY + (int) (Math.random() * 10 - 5));
                    Thread.sleep(20);  // Pausa breve entre cada movimiento
                }
                // Volver a la posición original al finalizar
                this.setLocation(originalX, originalY);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
    }
    
    private Login login = new Login();

    
    public VentanaLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Info1 = new javax.swing.JLabel();
        InfoUsuario = new javax.swing.JLabel();
        InfoContraseña = new javax.swing.JLabel();
        BotonLoguear = new javax.swing.JButton();
        TextoUsuario = new javax.swing.JTextField();
        MostrarContraseña = new javax.swing.JCheckBox();
        CampoContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        Info1.setText("Por favor, introduzca sus credenciales para acceder:");

        InfoUsuario.setText("Usuario");

        InfoContraseña.setText("Password");

        BotonLoguear.setText("Loguear");
        BotonLoguear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLoguearActionPerformed(evt);
            }
        });

        MostrarContraseña.setText("Mostrar");
        MostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InfoUsuario)
                    .addComponent(InfoContraseña))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextoUsuario)
                    .addComponent(BotonLoguear, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(CampoContraseña))
                .addGap(18, 18, 18)
                .addComponent(MostrarContraseña)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(Info1)
                .addGap(0, 67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Info1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoUsuario)
                    .addComponent(TextoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoContraseña)
                    .addComponent(MostrarContraseña)
                    .addComponent(CampoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(BotonLoguear)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonLoguearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLoguearActionPerformed
        // TODO add your handling code here:
          
        String username = TextoUsuario.getText();
        String password = CampoContraseña.getText();
        

        if(login.validacionUsuarios(username, password)){
            VentanaPrincipal principal = new VentanaPrincipal(username);
            principal.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Usuario o Contraseña incorrecta, vuelve a probarlo.", "Error",JOptionPane.ERROR_MESSAGE);
            TextoUsuario.setText("");
            CampoContraseña.setText("");
            vibrarPantalla();
        }
    }//GEN-LAST:event_BotonLoguearActionPerformed

    private void MostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarContraseñaActionPerformed
        // TODO add your handling code here:
        if (MostrarContraseña.isSelected()) {
            CampoContraseña.setEchoChar((char) 0);
        } else {
            CampoContraseña.setEchoChar('*');
        }
    }//GEN-LAST:event_MostrarContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLoguear;
    private javax.swing.JPasswordField CampoContraseña;
    private javax.swing.JLabel Info1;
    private javax.swing.JLabel InfoContraseña;
    private javax.swing.JLabel InfoUsuario;
    private javax.swing.JCheckBox MostrarContraseña;
    private javax.swing.JTextField TextoUsuario;
    // End of variables declaration//GEN-END:variables
}
